# Generated by Django 5.2.8 on 2025-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('admin', 'Администратор')], max_length=50, verbose_name='Роль')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('institute', models.CharField(max_length=100, verbose_name='Институт')),
                ('group', models.CharField(max_length=100, verbose_name='Группа')),
                ('course', models.CharField(max_length=100, verbose_name='Курс')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
