# Generated by Django 5.2.8 on 2025-12-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_gen_tasks', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('type', models.TextField(verbose_name='Тип задачи')),
                ('deadline', models.DateField(verbose_name='Дедлайн задачи')),
                ('assign_to', models.TextField(verbose_name='Кому предназначена задача')),
            ],
            options={
                'db_table': 'general_tasks',
            },
        ),
        migrations.CreateModel(
            name='StudentGeneralTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_done', 'Не выполнено'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='not_done', max_length=20)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_gen_task', models.ForeignKey(db_column='id_gen_task', on_delete=django.db.models.deletion.PROTECT, to='tasks.task')),
            ],
            options={
                'db_table': 'students_general_tasks',
                'unique_together': {('id_user', 'id_gen_task')},
            },
        ),
    ]
