# Generated by Django 5.2.8 on 2025-12-11 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgeneraltask',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дедлайн задачи'),
        ),
    ]
